### ISSUE TITLE
insert picture

### ISSUE THREAD

**Issue by paul-mesnilgrente** [yyjhao/sublime-text-markmon#6]
Hello,

I have tried to insert a picture in my markdown files but it does not work.

I wrote that :

```
![modele](modele.png "schéma")
```

modele.png is in the same folder of the markdown file. I know that markmon has an option --projectdir to personalize the path of the project but I do not know where to write it.

Thank you and have a nice day

**Comment by paul-mesnilgrente** [comment]
Any idea ? I can put my pictures on the internet but I do not like this solution, it takes too much time

**Comment by kreja** [comment]
go to Sublime Text → Preferences → Package Settings → Markmon → Settings(User) and configure like this:

```
{
    "stylesheet": "/path/to/style.css",
        ...,
    "projectdir": "/path/to/projectdir/"
}
```

**Comment by paul-mesnilgrente** [comment]
thank you very much, the browser print the picture :)

**Comment by paul-mesnilgrente** [comment]
another question about this issue, is it possible to say in this settings file.

``` json
{
    "projectdir": "the_folder_where_i_am_currently"
}
```

where "the_folder_where_i_am_currently" is the folder that I'm currently editing...
